### PR TITLE
Misc fixes.

### LINKED ISSUE #23: timeoutWait function doesn't work with ESP8266
The timeoutWait function uses:
`while((long)(micros() - resumeTime) < 0L); // (syntax is rollover-proof)`

This won't work with ESP8266 because it leaves the processor no time to do other things.
For ESP8266 it should be changed to a delay() call.
I use delay(10) and that works fine.

### LINKED ISSUE #38: printer.feedRows(1) prints 'J' in stead of a row feed, unknown firmware version
`printer.feedRows(1); `prints a J in stead of a row feed. 
I suspected my firmware version is older, however I don't know the firmware version. Setting PRINTER_FIRMWARE in Adafruit_Thermal.h to 0 didn't change the behavior! That is strange, because it should print new-lines in case of older versions that don't support the row-feed command.
I changed the header files in both these locations:

- /home/USER/.arduino15/staging/libraries/Adafruit_Thermal_Printer_Library-1.2.0.zip
- /home/USER/Arduino/libraries/Adafruit_Thermal_Printer_Library

I added the following lines in my code as a sanity check:
```
#if PRINTER_FIRMWARE >=268
#error "PRINTER_FIRMWARE>=268"
#endif
```
It gives the error when I don't edit the header file and doesn't when I set it to 0. So that means it should be compiled using that define. I deleted the cache folder and restarted arduino ide several times. But it still prints J

I use printer #597.
This is what the sticker says:
```
Model: CSN-A2
S/N Z1912110420
```
The test page printed by the printer doesn't have a firmware version number. This is what I see:
```
Selftest
System: A2
Version: GV.16.08 20190822_R
[...]
MAX dots:80
Heat time:774
[...]
Selftest Finished
```
I have ubuntu 20.
I use esp32 DOIT devkit.
Printing text works well.
Printing bitmaps works well too, but I do see thin horizontal white lines through the image even after setting heating time to 255.

### PR DESCRIPTION
**Pull request by caternuson**
A couple of fixes here.

* Fix #23. The busy wait loop was causing WDT reset on ESP8266. Added a `delay(0)` in the loop to allow ESP8266's implementation to yield as needed. This way don't need any pre-processor logic.
* Fix #38. Was not able to reproduce this, but based on conversation in issue thread it was related to calling an unsupported option `DC2 *` in `begin()`. Moved that configuration to a new function `setPrintDensity()` and then don't call it by default. Resulting prints look fine without it.

Here's an example WDT reset just for records:
Screenshot from 2021-04-09 13-49-52

### CODE REVIEW

File: Adafruit_Thermal.cpp [hunk 1]
```diff
@@ -81,11 +81,13 @@ void Adafruit_Thermal::timeoutSet(unsigned long x) {
 // This function waits (if necessary) for the prior task to complete.
 void Adafruit_Thermal::timeoutWait() {
   if (dtrEnabled) {
-    while (digitalRead(dtrPin) == HIGH)
-      ;
+    while (digitalRead(dtrPin) == HIGH) {
+      delay(0);
```
Comment (ladyada) [inline Adafruit_Thermal.cpp:85]: can you make these delay(1) or yield()?

**Review by ladyada — CHANGES_REQUESTED** [review]

File: Adafruit_Thermal.cpp (hunk 1 above)
Comment (caternuson) [reply Adafruit_Thermal.cpp:85]: Sure, can bump up value. Was avoiding `yield()` based on this comment:
https://github.com/adafruit/Adafruit-Thermal-Printer-Library/pull/26#issuecomment-304168712
Idea being that ESP8266's `delay()` calls `yield()` under the hood. Hopefully using `delay()` is more universal.

Comment (ladyada) [reply Adafruit_Thermal.cpp]: yield is most like delay(0), delay(1) of course delays. ill say i use yield() in libraries and never heard a complaint

Comment (caternuson) [reply Adafruit_Thermal.cpp]: it may be old lore? all the BSPs have caught up now? `yield` makes more sense than `delay`, was just wanting to avoid preprocessor logic if possible.

Comment (ladyada) [reply Adafruit_Thermal.cpp]: yeah all BSPs have caught up, that was 4 years ago :D

Comment (caternuson) [reply Adafruit_Thermal.cpp]: works4me

**Review by ladyada — APPROVED** [review]

**Comment by caternuson** [comment]
ESP8266 testing for the record. Previously it would WDT timeout on the bitmap print.

esp8266_test
